services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Docker1433-"
    ports:
      - "1433:1433"
    volumes:
      - db:/var/opt/mssql

  backend:
    build:
      context: ./backend
      dockerfile: Xpensoft.Api/Dockerfile
    container_name: backend
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ClientUrl: "http://localhost:4200"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=xpensoft;User=sa;Password=Docker1433-;TrustServerCertificate=True;"
      Jwt__Issuer: "Xpensoft"
      Jwt__Key: "4a2c7f29-f10b-4087-bad3-649e4cec8055"
    ports:
      - "5100:8080"

volumes:
  db:
