name: Build and deploy ASP.Net Core app to Azure Web App - xpensoft2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      # .NET SETUP
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.x"

      # RESTORE + BUILD
      - name: Restore
        run: dotnet restore backend/Xpensoft.Api.slnx

      - name: Build
        run: dotnet build backend/Xpensoft.Api.slnx -c Release --no-restore

      # TESTS
      - name: Run Unit Tests
        run: dotnet test backend/Xpensoft.Tests --no-build

      - name: Run Integration Tests
        run: dotnet test backend/Xpensoft.IntegrationTests --no-build

      # PUBLISH API PROJECT
      - name: Publish API Project
        run: dotnet publish backend/Xpensoft.Api/Xpensoft.Api.csproj -c Release -o publish

      # NODE SETUP
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      # BUILD ANGULAR
      - name: Build Angular
        run: |
          cd frontend
          npm install
          npm run build

      # COPY ANGULAR → API
      - name: Copy Angular to wwwroot
        run: |
          mkdir -p publish/wwwroot
          cp -r frontend/dist/frontend/browser/* publish/wwwroot

      # ARTIFACT
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2E453F6CFD5D4B33A6A7950FD23CE56B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_331179E36CCA4A0A82DE05D6EDF36A2A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2BAF3209B6234AFC93AD1CFC8AAB8325 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "xpensoft2"
          slot-name: "Production"
          package: .
